### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by Miz85**
Hi everyone, 

I'm submitting tests for the meetup module :)

Cheers,
Nazim

### CODE REVIEW

**Comment by PatrickHeneise** [comment]
:+1: sounds good. But please take @BcnJS out of the tests, you're spamming a real account ;)

**Comment by Miz85** [comment]
Hey @PatrickHeneise, 

Where do you see the @BcnJs account ?

**Comment by PatrickHeneise** [comment]
Not sure if you have it in the code, just realised the ~20 messages on Twitter.

**Comment by Miz85** [comment]
Hey guys, anyone wants to merge this one ? I think it's all okay. If anyone tried the meetup integration already I'd love some feedback ^^

**Pull request merged**
